
C:\Users\Vatan\Desktop\py\11\ePubSwift-main>pyinstaller --onefile --windowed --name="ePub_Swift" --icon="assets/icons/app_icon.png" --add-data="assets;assets" --additional-hooks-dir=hooks main.py
40 DEPRECATION: Running PyInstaller as admin is not necessary nor sensible. Run PyInstaller from a non-administrator terminal. PyInstaller 7.0 will block this.
250 INFO: PyInstaller: 6.14.2, contrib hooks: 2025.7
250 INFO: Python: 3.9.13
260 INFO: Platform: Windows-10-10.0.19041-SP0
260 INFO: Python environment: C:\Users\Vatan\AppData\Local\Programs\Python\Python39
262 INFO: wrote C:\Users\Vatan\Desktop\py\11\ePubSwift-main\ePub_Swift.spec
266 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\pyinstaller.exe',
 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib',
 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39',
 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages',
 'C:\\Users\\Vatan\\Desktop\\py\\11\\ePubSwift-main']
693 INFO: Appending 'datas' from .spec
694 INFO: checking Analysis
695 INFO: Building Analysis because Analysis-00.toc is non existent
695 INFO: Running Analysis Analysis-00.toc
695 INFO: Target bytecode optimization level: 0
696 INFO: Initializing module dependency graph...
697 INFO: Initializing module graph hook caches...
729 INFO: Analyzing modules for base_library.zip ...
1664 INFO: Processing standard module hook 'hook-heapq.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
2343 INFO: Processing standard module hook 'hook-encodings.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
3957 INFO: Processing standard module hook 'hook-pickle.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
5524 INFO: Caching module dependency graph...
5606 INFO: Looking for Python shared library...
5619 INFO: Using Python shared library: C:\Users\Vatan\AppData\Local\Programs\Python\Python39\python39.dll
5619 INFO: Analyzing C:\Users\Vatan\Desktop\py\11\ePubSwift-main\main.py
5628 INFO: Processing standard module hook 'hook-PySide6.py' from 'C:\\Users\\Vatan\\Desktop\\py\\11\\ePubSwift-main\\hooks'
5899 INFO: Processing standard module hook 'hook-shiboken6.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
6159 INFO: Processing standard module hook 'hook-PySide6.QtNetwork.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
8005 INFO: Processing standard module hook 'hook-PySide6.QtCore.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
9395 INFO: Processing standard module hook 'hook-PySide6.QtWidgets.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
10850 INFO: Processing standard module hook 'hook-PySide6.QtGui.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
11492 INFO: Processing module hooks (post-graph stage)...
11516 INFO: Performing binary vs. data reclassification (415 entries)
11964 INFO: Looking for ctypes DLLs
11969 INFO: Analyzing run-time hooks ...
11971 INFO: Including run-time hook 'pyi_rth_pyside6.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks'
11974 INFO: Processing pre-find-module-path hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path'
11977 INFO: Processing standard module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PyInstaller\\hooks'
11999 INFO: Creating base_library.zip...
12112 INFO: Looking for dynamic libraries
12327 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\shiboken6']
12328 INFO: Extra DLL search directories (PATH): ['C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\PySide6']
19262 WARNING: Library not found: could not resolve 'LIBPQ.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\plugins\\sqldrivers\\qsqlpsql.dll'.
19278 WARNING: Library not found: could not resolve 'fbclient.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\plugins\\sqldrivers\\qsqlibase.dll'.
19322 WARNING: Library not found: could not resolve 'Qt63DQuickLogic.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\qml\\Qt3D\\Logic\\3dquicklogicplugin.dll'.
19330 WARNING: Library not found: could not resolve 'OCI.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\plugins\\sqldrivers\\qsqloci.dll'.
19338 WARNING: Library not found: could not resolve 'Qt63DQuickScene3D.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19351 WARNING: Library not found: could not resolve 'MIMAPI64.dll', dependency of 'C:\\Users\\Vatan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PySide6\\plugins\\sqldrivers\\qsqlmimer.dll'.
19445 INFO: Warnings written to C:\Users\Vatan\Desktop\py\11\ePubSwift-main\build\ePub_Swift\warn-ePub_Swift.txt
19488 INFO: Graph cross-reference written to C:\Users\Vatan\Desktop\py\11\ePubSwift-main\build\ePub_Swift\xref-ePub_Swift.html
19538 INFO: checking PYZ
19539 INFO: Building PYZ because PYZ-00.toc is non existent
19540 INFO: Building PYZ (ZlibArchive) C:\Users\Vatan\Desktop\py\11\ePubSwift-main\build\ePub_Swift\PYZ-00.pyz
19891 INFO: Building PYZ (ZlibArchive) C:\Users\Vatan\Desktop\py\11\ePubSwift-main\build\ePub_Swift\PYZ-00.pyz completed successfully.
19926 INFO: checking PKG
19926 INFO: Building PKG because PKG-00.toc is non existent
19927 INFO: Building PKG (CArchive) ePub_Swift.pkg
84006 INFO: Building PKG (CArchive) ePub_Swift.pkg completed successfully.
84034 INFO: Bootloader C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
84034 INFO: checking EXE
84035 INFO: Building EXE because EXE-00.toc is non existent
84035 INFO: Building EXE from EXE-00.toc
84036 INFO: Copying bootloader EXE to C:\Users\Vatan\Desktop\py\11\ePubSwift-main\dist\ePub_Swift.exe
84042 INFO: Copying icon to EXE
Traceback (most recent call last):
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\icon.py", line 50, in normalize_icon_type
    from PIL import Image as PILImage
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 231, in _console_script_run
    run()
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 1282, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 1220, in build
    exec(code, spec_namespace)
  File "C:\Users\Vatan\Desktop\py\11\ePubSwift-main\ePub_Swift.spec", line 19, in <module>
    exe = EXE(
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 678, in __init__
    self.__postinit__()
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\datastruct.py", line 184, in __postinit__
    self.assemble()
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 791, in assemble
    self._retry_operation(icon.CopyIcons, build_name, self.icon)
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\api.py", line 1061, in _retry_operation
    return func(*args)
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\utils\win32\icon.py", line 206, in CopyIcons
    srcpath = normalize_icon_type(srcpath, ("exe", "ico"), "ico", config.CONF["workpath"])
  File "C:\Users\Vatan\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\icon.py", line 54, in normalize_icon_type
    raise ValueError(
ValueError: Received icon image 'C:\Users\Vatan\Desktop\py\11\ePubSwift-main\assets\icons\app_icon.png' which exists but is not in the correct format. On this platform, only ('exe', 'ico') images may be used as icons. If Pillow is installed, automatic conversion will be attempted. Please install Pillow or convert your 'png' file to one of ('exe', 'ico') and try again.

C:\Users\Vatan\Desktop\py\11\ePubSwift-main>
